### ISSUE TITLE
Request: change TargetTemperature from Long to Double

### ISSUE THREAD

**Issue by mikecroft** [bwssytems/nest-controller#1]
If the thermostat is in Celsius, the target temperature can be set in half degrees, [but that's not currently supported as the type is `Long`](https://github.com/bwssytems/nest-controller/blob/master/src/main/java/com/bwssystems/nest/protocol/status/SharedDetail.java#L76).

Thanks for a great library, btw, this has saved me a lot of time!

**Comment by bwssytems** [comment]
Thanks will include that

**Comment by bwssytems** [comment]
Also, very I saw your had federalization errors, could you share those? Another user of the bridge that uses this library is having other deserialization issues that I was trying to fix in 1.0.10

**Comment by mikecroft** [comment]
Looks like this is the relevant bit:

```
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:868)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.bwssystems.nest.protocol.status.DeviceDeserializer.deserialize(DeviceDeserializer.java:23)
	at com.bwssystems.nest.protocol.status.DeviceDeserializer.deserialize(DeviceDeserializer.java:14)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at com.bwssystems.nest.controller.Nest._getStatus(Nest.java:54)
	at com.bwssystems.nest.controller.Nest.<init>(Nest.java:45)
	at io.mikecroft.home.nest.TemperatureMonitor.init(TemperatureMonitor.java:53)
```

I'm running this in Payara Micro as a `@Startup` EJB and there were a couple of things that hinted at it being a timing issue. I'm not sure, though, since it works perfectly with 1.0.0 and the only difference is increasing the version to 1.0.10.

**Comment by mikecroft** [comment]
I created a gist with the full log
https://gist.github.com/mikecroft/93ac16825af943467eb37a70691e5908

**Comment by bwssytems** [comment]
For your use, I would keep it at version 1.0.0 until I merge your changes in. I think by taking out fields for deserialization is causing more issues.

**Comment by mikecroft** [comment]
Cool, no worries :) I can just use my patched version in the meantime!
